/** Curated lists — merged with values already in your inventory on the form. */
export const MEDICINE_CATEGORIES = [
  "Antibiotics",
  "Analgesics & Pain Relief",
  "Antipyretics",
  "Antihistamines & Allergy",
  "Vitamins & Supplements",
  "Cardiovascular",
  "Diabetes & Endocrine",
  "Gastrointestinal",
  "Respiratory",
  "Dermatological",
  "Ophthalmic",
  "Dental & Oral Care",
  "Women's Health",
  "Pediatric",
  "Vaccines & Immunization",
  "Medical Supplies & Devices",
  "Herbal & Traditional",
  "Oncology",
  "Psychiatric & Neurological",
  "IV Fluids & Injectables",
] as const;

export const MEDICINE_MANUFACTURERS = [
  "Pfizer",
  "GSK",
  "Novartis",
  "Sanofi",
  "Merck",
  "Bayer",
  "AstraZeneca",
  "Roche",
  "Johnson & Johnson",
  "Abbott",
  "Cipla",
  "Sun Pharma",
  "Cadila (Zydus)",
  "Lupin",
  "Ethiopian Pharmaceuticals",
  "Addis Pharmaceutical Factory",
  "Adigrat Pharmaceutical",
  "Kaliti Pharmaceutical",
  "Novamed",
  "Philadelphia Pharmaceuticals",
  "Tana Pharmaceutical",
  "Universal Pharmaceutical",
] as const;

export const MEDICINE_OPTION_OTHER = "__other__";
